import{a as y,S as h,i}from"./assets/vendor-Epugobq5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const L="49374949-4ded30d1f71c5277e2f481102",w="https://pixabay.com/api/";let f=1;const q=15;function v(){f=1}function P(){f+=1}async function S(t){const e={key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:f,per_page:q};try{return(await y.get(w,{params:e})).data}catch(a){throw console.error("Fetch images error:",a.message),a}}function b(){const t=document.querySelector(".gallery");t.innerHTML=""}function I(t){const e=document.querySelector(".gallery"),a=t.map(s=>`
    <li class="gallery-item">
      <a href="${s.largeImageURL}">
        <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" />
        <div class="info">
          <p>Likes ${s.likes}</p>
          <p>Views ${s.views}</p>
          <p>Comments ${s.comments}</p>
          <p>Downloads ${s.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");e.insertAdjacentHTML("beforeend",a)}const g=document.querySelector(".form"),$=document.querySelector(".loader"),n=document.querySelector(".load-more");let u="",m=0,c=0;const O=new h(".gallery a",{captionsData:"alt",captionDelay:250});g.addEventListener("submit",async t=>{t.preventDefault();const e=t.target.elements.searchQuery.value.trim();if(!e)return i.error({message:"Please enter a search query!",position:"topLeft"});e!==u&&(v(),b(),n.classList.add("hidden"),u=e,c=0),await p(),g.reset()});n.addEventListener("click",async()=>{P(),await p(!0)});async function p(t=!1){d(!0);try{const e=await S(u);if(d(!1),e.hits.length===0&&c===0)return n.classList.add("hidden"),i.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft"});I(e.hits),O.refresh(),c+=e.hits.length,m=e.totalHits,c<m?n.classList.remove("hidden"):(n.classList.add("hidden"),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"})),t&&A()}catch{d(!1),i.error({message:"An error occurred. Please try again.",position:"topLeft"})}}function d(t){$.classList.toggle("hidden",!t),n.classList.toggle("hidden",t)}function A(){const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
